sudo: required
services:
  - docker

before_install:
  - docker build -t expollux/m-test -f ./client/Dockerfile.dev ./client

script:
  - docker run expollux/m-test npm test -- --coverage


after_success:
  - docker build -t expollux/multi-client ./client
  - docker build -t expollux/multi-nginx ./nginx
  - docker build -t expollux/multi-server ./server
  - docker build -t expollux/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push expollux/multi-client
  - docker push expollux/multi-nginx
  - docker push expollux/multi-server
  - docker push expollux/multi-worker