env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

sudo: required
services:
  - docker

before_install:
  - docker build -t expollux/m-test -f ./client/Dockerfile.dev ./client

script:
  - docker run expollux/m-test npm test -- --coverage


after_success:
  - docker build -t expollux/multi-client:$COMMIT ./client
  - docker build -t expollux/multi-nginx:$COMMIT ./nginx
  - docker build -t expollux/multi-server:$COMMIT ./server
  - docker build -t expollux/multi-worker:$COMMIT ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push expollux/multi-client
  - docker push expollux/multi-nginx
  - docker push expollux/multi-server
  - docker push expollux/multi-worker