version: '3'
services:
  redis:
    image: 'redis:latest'
  postgres:
    image: 'postgres:10'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx: 
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    image: stephengrider/multi-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
    depends_on:
      - redis
      - postgres
    restart: on-failure
  client:
    image: stephengrider/multi-client
    depends_on:
      - api
      - nginx
    restart: on-failure
  worker:
    image: stephengrider/multi-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: on-failure
